version: '3'
services:
  triponometry-backend:
    build: .
    container_name: 'triponometry-backend'
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - backend
      - db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=triponometry-db
  mongodb:
    image: mongo:latest
    container_name: 'mongodb-container'
    environment:
      - MONGO_INITDB_DATABASE=triponometry-db
    ports:
      - 27017:27017
    networks:
      - db
networks:
  db:
  backend: