triponometry:
  weather:
    url: http://api.openweathermap.org
    api-key: 89d747aabdeffa15aa1022f415cb3960
  google:
    ##api-key: AIzaSyDoy_IiMQhsVTF_7ViKzFUa8r9ir7BADBw -> MAGA
    api-key: AIzaSyDYvqEW16HdPdIRXCncIIGtjQ-4bbQk0i0
  distance:
    url: https://maps.googleapis.com/maps/api/distancematrix/json
  genetic-algorithm:
    individuals-qty: 1000
    cycles-qty: 100
  aws:
    url: https://yji8each99.execute-api.us-east-1.amazonaws.com/dev
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb+srv://triponometry-user:triponometry@cluster0.jrgwcxg.mongodb.net/?retryWrites=true&w=majority
      database: triponometry-db